services:
  #database section
  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD:  "Passw0rd!"
      ACCEPT_EULA: "Y"
    restart: no
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data
    ports:
      - "1435:1433"
    
  #productdb mysql
  productdb:
    container_name: productdb
    environment:
      MYSQL_ROOT_PASSWORD:  "Passw0rd!"
    restart: no
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
        
  #customerdb postgres
  customerdb:
      container_name: customerdb
      environment:
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD:  "admin1234"
        POSTGRES_DB: "CustomerDb"
      restart: no
      volumes:
      - postgres_data:/var/lib/postgresql/data
      ports:
      - "5433:5432"

  #basketdb redis
  basketdb:
    container_name: basketdb
    restart: no
    ports:
      - "6379:6379"
        
  #rabbitmq
  rabbitmq:
      container_name: rabbitmq
      ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI
      restart: no
      
  #microservices api sections
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=productdb;Port=3306;Database=ProductDb;Uid=root;Pwd=Passw0rd!;"
    depends_on:
      - productdb
    ports:
        - "6002:80"
    restart: "no"
    
  customer.api:
    container_name: customer.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=customerdb;Port=5432;Database=CustomerDb;User Id=admin;Password=admin1234;"
    depends_on:
      - customerdb
    ports:
        - "6003:80"
    restart: "no"
    
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "Redis:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
        - "6004:80"
    restart: "no"
    
  order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=orderdb;Database=OrderDB;User Id=sa;Password=Passw0rd!;MultipleActiveResultSets=true"
    depends_on:
      - orderdb
    ports:
      - "6005:80"
    restart: "no"
