services:
  #database section
  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD:  "Passw0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data
    ports:
      - "1435:1433"
    
  #productdb mysql
  productdb:
    container_name: productdb
    environment:
      MYSQL_ROOT_PASSWORD:  "Passw0rd!"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  #microservices api sections
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - "ConnectionStrings:DefaultConnection=Server=productdb;Port=3306;Database=ProductDb;Uid=root;Pwd=Passw0rd!;"
    depends_on:
      - productdb
    ports:
        - "6002:80"
    restart: "always"
