services:
  #database section
  orderdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  productdb:
    image: mysql:8.0.29
    
  customerdb:
    image: postgres:17-alpine
    
  basketdb:
    image: redis:alpine
    
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI
        
  inventorydb:
    image: postgres:17-alpine
    
  #microservices API section
  product.api:
    image: ${DOCKER_REGISTRY-}product-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Product.API/Dockerfile
      
  customer.api:
    image: ${DOCKER_REGISTRY-}customer-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Customer.API/Dockerfile
      
  basket.api:
    image: ${DOCKER_REGISTRY-}basket-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile
      
  order.api:
    image: ${DOCKER_REGISTRY-}order-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      
  inventory.product.api:
    image: ${DOCKER_REGISTRY-}inventory-product-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Inventory.Production.API/Dockerfile
      
  inventory.grpc:
    image: ${DOCKER_REGISTRY-}inventory-grpc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Inventory.GrpcService/Inventory.GrpcService/Dockerfile
      
  ocelot.apigw:
    image: ${DOCKER_REGISTRY-}ocelot.apigw:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile 
      
#network section
networks:
  default:
    name: microservices
    driver: bridge
    
#volumes section
volumes:
  sqlserver_data:
    name: sqlserver_data
  mysql_data:
    name: mysql_data
  postgres_data:
    name: postgres_data
  postgres_data_inventory:
    name: postgres_data_inventory
    
    